img = imread("img\sepatu.jpg");
result1 = laplaceOfGaussian(img,1.4);
result2 = sobel_operator(img);
result3 = prewitt_operator(img);
result4 = roberts(img);
result5 = canny_operator(img);
result6 = laplace(img);
segmented1 = segmentation(result1,img);
segmented2 = segmentation(result2,img);
segmented3 = segmentation(result3,img);
segmented4 = segmentation(result4,img);
segmented5 = segmentation(result5,img);
segmented6 = segmentation(result6,img);
figure;
    subplot(2, 3, 1); imshow(segmented1); title('LoG');
    subplot(2, 3, 2); imshow(segmented2); title('sobel');
    subplot(2, 3, 3); imshow(segmented3); title('prewitt');
    subplot(2, 3, 4); imshow(segmented4); title('roberts');
    subplot(2, 3, 5); imshow(segmented5); title('canny');
    subplot(2, 3, 6); imshow(segmented6); title('laplace');